# Generated by Django 5.0.6 on 2024-09-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(default=1, verbose_name='История компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(default=1, verbose_name='Реквизиты компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео о компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_text',
            field=models.TextField(verbose_name='Информация о компании'),
        ),
    ]
