# Generated by Django 5.0.6 on 2024-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0003_companyinfo_history_companyinfo_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='news/')),
                ('published_date', models.DateField()),
            ],
        ),
    ]
