# Generated by Django 5.0.6 on 2024-09-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0005_remove_review_name_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees_photos/'),
        ),
    ]
